spring.application.name=SpringAIStart

server.port=8080

#\u914D\u7F6E Deepseek\u7684\u57FA\u7840URL\uFF0C\u5BC6\u94A5\uFF0C\u4F7F\u7528\u6A21\u578B
spring.ai.deepseek.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
spring.ai.deepseek.api-key=${DEEPSEEK_API_KEY}
spring.ai.deepseek.chat.options.model=deepseek-v3.2

#\u4ECB\u4E8E0\u548C2\u4E4B\u95F4\uFF0C0\u8868\u793A\u968F\u673A\u6027\u6700\u5C0F\uFF0C2\u8868\u793A\u968F\u673A\u6027\u6700\u5927
spring.ai.deepseek.chat.options.temperature=0.8
